PhoneAdvisor/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from PhoneAdvisor.views import HomePageView,SearchView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePageView.as_view(), name= 'home'),
    path('user_management/', include('user_management.urls')),
    path('smartphone/', include('smartphone.urls')),
    path('article/', include('article.urls')),
    path('search', SearchView.as_view(), name='global-search'),

]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

article/urls.py
from django.conf.urls.static import static
from django.urls import path
from article import views
from django.conf import settings
app_name = 'article'


urlpatterns = [
        path('add', views.CreateArticleView.as_view(), name='article-add'),
        path('list', views.ListArticleView.as_view(), name='article-list'),
        path('<int:pk>/update', views.UpdateArticleView.as_view(), name='article-update'),
        path('<int:pk>/delete', views.DeleteArticleView.as_view(), name='article-delete'),
        path('<int:pk>/detail', views.ArticleDetail.as_view(), name='article-detail'),
        path('like', views.ajax_like_button, name='article-like'),

]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

user_management/urls.py
from django.conf.urls.static import static
from django.urls import path
from user_management import views
from django.conf import settings
app_name = 'user_management'


urlpatterns = [
        path('registration', views.UserCreateView.as_view(), name='user-register'),
        path('login', views.LoginUserView.as_view(), name='user-login'),
        path('logout', views.LogoutUserView.as_view(), name='user-logout'),
        path('list', views.ListUserView.as_view(), name='user-list'),
        path('profile/<int:pk>', views.ProfileView.as_view(), name='user-overview'),
        path('profile/<int:pk>/update', views.UserUpdateView.as_view(), name='user-update'),
        path('profile/<int:pk>/delete', views.UserDeleteView.as_view(), name='user-delete'),
        path('personal-profile/create', views.UserProfileCreateView.as_view(), name='user-profile-create'),
        path('personal-profile/<int:pk>/update', views.UserProfileUpdateView.as_view(), name='user-profile-update'),
        path('personal-profile/<int:pk>/delete', views.UserProfileDeleteView.as_view(), name='user-profile-delete'),
        path('check-username', views.check_username_is_unique, name='check-username'),

]

user_management/models.py
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ObjectDoesNotExist
from django.db import models
from django.utils.translation import gettext_lazy as _
from PhoneAdvisor import settings


class PlatformUser(AbstractUser):
    email = models.EmailField(_('email address'), unique=True)

    # AbstractUser._meta.get_field('email')._unique = True

    class Meta:
        verbose_name = _('platform_user')
        verbose_name_plural = _('platform_users')

    @property
    def has_profile(self):
        try:
            assert self.profile
            return True
        except ObjectDoesNotExist:
            return False

    @property
    def category(self):
        return "3"


class Profile(models.Model):
    birthday = models.DateField(_('Compleanno YYYY-MM-DD'), null=True, blank=True)
    profile_img = models.ImageField(('Immagine del Profilo'), upload_to='profile_images')
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='profile')

user_management/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Row, Column, Div
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django import forms
from django.utils.translation import gettext_lazy as _

from user_management.models import PlatformUser, Profile


class RegistrationForm(UserCreationForm):
    """
    Registration form where the user entering: username, email, name, last name
    and password can create a new profile to access the application
    """
    email = forms.EmailField(required=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].widget.attrs['placeholder'] = 'example@example.com'
        self.fields['username'].widget.attrs['placeholder'] = 'Username'
        self.fields['password1'].widget.attrs['placeholder'] = 'Password'
        self.fields['password2'].widget.attrs['placeholder'] = _('repeat password')
        self.fields['first_name'].widget.attrs['placeholder'] = _('first name')
        self.fields['last_name'].widget.attrs['placeholder'] = _('last name')
        self.helper = FormHelper()
        self.helper.form_id = 'utente-crispy-form'
        self.helper.form_method = 'POST'

        self.helper.layout = Layout(
            Row(
                Column('username', css_class='form-group m-3'),

                Div(css_id='username-check'),

                Column('first_name', css_class='form-group m-3'),
                Column('last_name', css_class='form-group m-3'),
                css_class='form-row'
            ),
            Row(
                Column('email', css_class='form-group m-3'),
                css_class='form-row'
            ),
            Row(
                Column('password1', css_class='form-group m-3'),
                Column('password2', css_class='form-group m-3'),
                css_class='form-row'
            ),
        )

    class Meta:
        model = PlatformUser
        fields = ("email", "username", "first_name", "last_name", 'password1', 'password2')



class LoginForm(AuthenticationForm):
    """
    Login form where an already registered user can enter the username and password to authenticate
    """

    def __init__(self, request=None, *args, **kwargs):
        """
        The 'request' parameter is set for custom auth use by subclasses.
        The form data comes in via the standard 'data' kwarg.
        """
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'utente-crispy-form'
        self.helper.form_method = 'POST'
        self.request = request
        self.user_cache = None

        self.helper.layout = Layout(
            Row(
                Column('username', css_class='form-group mb-0'),
                css_class='form-row'
            ),
            Row(
                Column('password', css_class='form-group mb-0'),
                css_class='form-row'
            ),
        )


class UserProfileForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_id = 'utente-crispy-form'
        self.helper.form_method = 'POST'

    class Meta:
        model = Profile
        fields = ('birthday', 'profile_img')

user_management/views.py
from django.contrib.auth import login
from django.contrib.auth.views import LoginView, LogoutView
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, UpdateView, DetailView, DeleteView, ListView

from user_management.decorators import user_owner_only, has_profile_only, has_not_profile
from user_management.forms import LoginForm, RegistrationForm, UserProfileForm
from user_management.models import PlatformUser, Profile


class UserCreateView(CreateView):
    """
    View per la creazione di un nuovo utente
    """
    form_class = RegistrationForm
    template_name = 'registration/registration_form.html'
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        response = super(UserCreateView, self).form_valid(form)
        login(self.request, self.object)
        return response


class LoginUserView(LoginView):
    """
    View che implementa la schermata di login
    """
    form_class = LoginForm
    template_name = 'registration/login.html'
    success_url = reverse_lazy('home')


class LogoutUserView(LogoutView):
    """
    View che implementa la schermata di logout
    """
    template_name = 'registration/logged_out.html'
    success_url = reverse_lazy('user_management:user-login')


class ProfileView(DetailView):
    """
    View per visualizzare una panoramica dell'account di un utente
    """
    template_name = 'user_management/user_overview.html'
    model = PlatformUser


class UserUpdateView(UpdateView):
    """
    View per la modifica di un utente esistente
    """
    template_name = 'user_management/user_update.html'
    model = PlatformUser
    form_class = RegistrationForm

    def get_success_url(self):
        user_id = self.kwargs['pk']
        return reverse_lazy('user_management:user-overview', kwargs={'pk': user_id})


@method_decorator(user_owner_only, name='dispatch')
class UserDeleteView(DeleteView):
    """
    View per l'eliminazione di un utente
    """

    model = PlatformUser
    success_url = reverse_lazy('user_management:user-login')


@method_decorator(has_not_profile, name='dispatch')
class UserProfileCreateView(CreateView):
    """
    View per la creazione di un profilo utente
    """
    template_name = 'user_management/user_profile_create.html'
    form_class = UserProfileForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(UserProfileCreateView, self).form_valid(form)

    def get_success_url(self):
        user_id = self.request.user.pk
        return reverse_lazy('user_management:user-overview', kwargs={'pk': user_id})


@method_decorator(user_owner_only, name='dispatch')
@method_decorator(has_profile_only, name='dispatch')
class UserProfileUpdateView(UpdateView):
    """
    View per la modifica di un profilo utente
    """
    template_name = 'user_management/user_profile_update.html'
    form_class = UserProfileForm
    model = PlatformUser

    def get_object(self, queryset=None):
        return Profile.objects.get(pk=self.request.user.profile.pk)

    def get_success_url(self):
        user_id = self.request.user.pk
        return reverse_lazy('user_management:user-overview', kwargs={'pk': user_id})


@method_decorator(user_owner_only, name='dispatch')
@method_decorator(has_profile_only, name='dispatch')
class UserProfileDeleteView(DeleteView):
    """
    View per l'eliminazione del profilo (ma non dell'account) di un utente
    """

    model = Profile

    def get_object(self, queryset=None):
        return Profile.objects.get(pk=self.request.user.profile.pk)

    def get_success_url(self):
        user_id = self.request.user.pk
        return reverse_lazy('user_management:user-overview', kwargs={'pk': user_id})


class ListUserView(ListView):
    """
    View per la visualizzazione di una lista di utenti
    """
    template_name = 'user_management/user_list.html'
    model = PlatformUser
    ordering = ['username']

    def get_queryset(self):
        ordering = self.request.GET.get('sort', 'username')
        if ordering != 'has_profile':
            return PlatformUser.objects.order_by(ordering).exclude(pk=1)
        else:
            return [user for user in PlatformUser.objects.all().exclude(pk=1) if user.has_profile]


def check_username_is_unique(request):
    """
    Funzione ajax che controlla l'unicità dell'username scelto da un utente in fase di registrazione
    o di modifica dell'account
    :param request: richiesta ajax
    :return: variabile true se l'username è gia utilizzato false altrimenti
    """
    username = request.GET.get('username', False)
    data = {
        'is_used': True if PlatformUser.objects.filter(username=username) else False
    }
    return JsonResponse(data)

user_management/templates/user_management/user_list.html
{% extends 'base.html' %}
{% load static %}
{% block head_title %}
    Utenti
{% endblock %}

{% block title %}
    Lista Utenti
{% endblock %}
{% block content %}
    <div class="row justify-content-center">
        <div class="col-10">
            {%  if user.is_authenticated %}
                {%  include 'user_management/base/order_by.html' %}
            {% endif %}
            {% include 'user_management/base/base_list.html' %}
        </div>
    </div>
{% endblock %}

user_management/templates/user_management/user_overview.html
{%  extends 'base.html' %}
{% comment %}
Base template used to show user data (account).
{% endcomment %}


{% load static %}
{% load crispy_forms_tags %}
{% block head_title %}
    Profilo utente {{  object.username }}
{% endblock %}
{% block title %}
    {{  object.username }}
{% endblock %}
{% block content %}
    <div class="container-fluid">
        <div class="row rounded shadow">
            <div class="col-4">
                {% if object.has_profile %}
                    <h6 class="card-title font-bold">IMMAGINE DEL PROFILO </h6>
                    <img class ="card-img" src="{{ object.profile.profile_img.url }}" width="150px" height="300px">
                {% else %}
                    {% if  object == user %}
                        <h6 class="card-title">Crea un profilo per inserire un'immagine</h6>
                    {% else%}
                        <h6 class="card-title">Nessuna immagine del profilo </h6>
                    {% endif %}

                {% endif %}
            </div>
            <div class="col-8 d-flex align-items-center">
                <div class="container">
                    <div class="row">
                        <span class="font-bold">USERNAME : {{ object.username }}</span><br>
                    </div>
                    <div class="row">
                        <span class="font-bold">NOME : {{ object.fisrt_name }}</span><br>
                    </div>
                    <div class="row">
                        <span class="font-bold">COGNOME : {{ object.last_name }}</span><br>
                    </div>
                    <div class="row">
                        <span class="font-bold " style="word-break: break-word">EMAIL : {{ object.email }}</span><br>
                    </div>
                    <div class="row">
                        <div class="col">
                            <span class="font-bold">DATA DI ISCRIZIONE : </span>
                            <span class="font-bold">{{ object.date_joined|date:'l'}}</span><br>
                            <span class="font-bold">{{ object.date_joined|date:'d/m/Y' }}</span>
                        </div>

                    </div>

                    {% if object.has_profile and object.profile.birthday %}
                        <div class="row">
                            <div class="col">
                                <span class="text-center font-bold">DATA DI NASCITA : {{ object.profile.birthday }}</span>
                            </div>
                        </div>
                    {% endif %}

                </div>

            </div>
        </div>


        {% if object == user %}
            <div class="row justify-content-center p-3">
                <div class="col-lg-6 col-12 p-2">
                    <a class="card bg-warning text-white text-center m-1" href="{% url 'user_management:user-update' user.pk %}">
                        <div class="card-body m-1">
                            <h5 class="card-text m-1">Modifica account</h5>
                        </div>
                    </a>
                    <a class="card bg-danger text-white text-center trigger-btn m-1" id="card-delete-user"
                       data-bs-target="#AccountModal" data-bs-toggle="modal">
                        <div class="card-body m-1" style="cursor: pointer">
                            <h5 class="card-text m-1 ">Elimina account</h5>
                        </div>
                    </a>

                </div>

                <div class="col-lg-6 col-12 p-2">

                    {% if not object.has_profile %}

                        <a class="card bg-primary text-white text-center m-1" href="{% url 'user_management:user-profile-create' %}">
                            <div class="card-body m-1">
                                <h5 class="card-text m-1">Crea Profilo</h5>
                            </div>
                        </a>
                    {% else %}

                        <a class="card bg-primary text-white text-center m-1" href="{% url 'user_management:user-profile-update' object.pk %}">
                            <div class="card-body m-1">
                                <h5 class="card-text m-1">Modifica profilo</h5>
                            </div>
                        </a>
                        <a class="card bg-danger text-white text-center trigger-btn m-1" id="card-delete-profile"
                           data-bs-target="#ProfileModal" data-bs-toggle="modal" >
                            <div class="card-body m-1" style="cursor: pointer">
                                <h5 class="card-text m-1">Elimina profilo</h5>
                            </div>
                        </a>

                    {% endif %}
                </div>
            </div>
        {% endif %}
    </div>

    <div class="container">
        <div id="ProfileModal" tabindex="-1" class="modal fade">
            <div class="modal-dialog modal-confirm">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4>Vuoi davvero eliminare il tuo profilo ?<br> </h4>
                        <span>Perderai la tua immagine del profilo</span>
                    </div>
                    <form method="POST" action="{%  url 'user_management:user-profile-delete' object.pk %}">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <div class="modal-footer">
                            <input class='btn btn-danger' type="submit" value ='Elimina '>
                            <a class='btn btn-success' href="{% url 'user_management:user-overview' object.pk %}">Annulla</a>
                    </form>

                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div id="AccountModal" tabindex="-1" class="modal fade">
            <div class="modal-dialog modal-confirm">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4>Vuoi davvero eliminare il tuo account ? <br></h4>
                        <span>Gli articoli e le schede tecniche che hai inserito verranno eliminati</span>
                    </div>
                    <form method="POST" action="{%  url 'user_management:user-delete' object.pk %}">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <div class="modal-body">
                            <p>Questa azione non sarà reversibile</p>
                        </div>
                        <div class="modal-footer">
                            <input class='btn btn-danger' type="submit" value ='Elimina '>
                            <a class='btn btn-success' href="{% url 'user_management:user-overview' object.pk %}">Annulla</a>
                    </form>

                </div>
            </div>
        </div>

    </div>

{% endblock %}

user_management/templates/user_management/user_profile_create.html
{% extends 'base_operations.html' %}
{% load crispy_forms_tags %}
{% load static %}


{% block head_title %}Profilo{% endblock %}
{% block title %}Profile{% endblock %}

{% block mod_buttons %}
    <div class="row justify-content-center">
        <div class="col-lg-6 col-12 d-flex justify-content-center">
            <input class="btn btn-success" type="submit" value="Crea profilo">
        </div>
        <div class="col-lg-6 col-12 d-flex justify-content-center">
            <a class="btn btn-primary ml-3" href="{% url 'user_management:user-overview' user.pk%}">Ritorna alla panoramica</a>
        </div>
    </div>
{% endblock %}

user_management/templates/user_management/user_profile_update.html
{% extends 'base_operations.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block head_title %}Aggiorna il tuo profilo{% endblock %}
{% block title %}Aggiorna il tuo profilo{% endblock %}

{% block mod_buttons %}
    <div class="row justify-content-center">
        <div class="col-lg-6 col-12 d-flex justify-content-center">
            <input class="btn btn-success m-1" type="submit" value="Aggiorna il profilo">
        </div>
        <div class="col-lg-6 col-12 d-flex justify-content-center">
            <a class="btn btn-primary m-1" href="{% url 'user_management:user-overview' user.pk%}">Ritorna alla panoramica</a>
        </div>
    </div>
{% endblock %}

user_management/templates/user_management/user_update.html
{% extends 'base_operations.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block head_title %}Aggiorna il tuo account{% endblock %}
{% block title %}Aggiorna il tuo account{% endblock %}

{% block mod_buttons %}
    <div class="row justify-content-center">
        <div class="col-lg-6 col-12 d-flex justify-content-center">
            <input class="btn btn-success m-1" type="submit" value="Aggiorna account">
        </div>
        <div class="col-lg-6 col-12 d-flex justify-content-center">
            <a class="btn btn-primary m-1" href="{% url 'user_management:user-overview' user.pk%}">Ritorna alla panoramica</a>
        </div>
    </div>
{% endblock %}