PhoneAdvisor/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from PhoneAdvisor.views import HomePageView,SearchView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePageView.as_view(), name= 'home'),
    path('user_management/', include('user_management.urls')),
    path('smartphone/', include('smartphone.urls')),
    path('article/', include('article.urls')),
    path('search', SearchView.as_view(), name='global-search'),

]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

article/urls.py
from django.conf.urls.static import static
from django.urls import path
from article import views
from django.conf import settings
app_name = 'article'


urlpatterns = [
        path('add', views.CreateArticleView.as_view(), name='article-add'),
        path('list', views.ListArticleView.as_view(), name='article-list'),
        path('<int:pk>/update', views.UpdateArticleView.as_view(), name='article-update'),
        path('<int:pk>/delete', views.DeleteArticleView.as_view(), name='article-delete'),
        path('<int:pk>/detail', views.ArticleDetail.as_view(), name='article-detail'),
        path('like', views.ajax_like_button, name='article-like'),

]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

smartphone/urls.py
from django.conf.urls.static import static
from django.urls import path
from smartphone import views
from django.conf import settings
app_name = 'smartphone'


urlpatterns = [
        path('add', views.CreateSmartphoneView.as_view(), name='smartphone-add'),
        path('list', views.ListSmartphoneView.as_view(), name='smartphone-list'),
        path('<int:pk>/update', views.UpdateSmartphoneView.as_view(), name='smartphone-update'),
        path('<int:pk>/delete', views.DeleteSmartphoneView.as_view(), name='smartphone-delete'),
        path('<int:pk>/detail', views.SmartphoneDetail.as_view(), name='smartphone-detail'),
        path('check-smartphone-name', views.check_smartphone_name_is_unique, name='check-smartphone-name'),
        # path('rate', views.rate_smartphone, name='rate-smartphone'),
        # path('search', views.SmartphoneSearchView.as_view(), name='smartphone-search'),
        path('compare/<int:first_pk>/<int:second_pk>/<int:third_pk>', views.CompareSmartphoneView.as_view(), name='smartphone-compare'),

]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

user_management/urls.py
from django.conf.urls.static import static
from django.urls import path
from user_management import views
from django.conf import settings
app_name = 'user_management'


urlpatterns = [
        path('registration', views.UserCreateView.as_view(), name='user-register'),
        path('login', views.LoginUserView.as_view(), name='user-login'),
        path('logout', views.LogoutUserView.as_view(), name='user-logout'),
        path('list', views.ListUserView.as_view(), name='user-list'),
        path('profile/<int:pk>', views.ProfileView.as_view(), name='user-overview'),
        path('profile/<int:pk>/update', views.UserUpdateView.as_view(), name='user-update'),
        path('profile/<int:pk>/delete', views.UserDeleteView.as_view(), name='user-delete'),
        path('personal-profile/create', views.UserProfileCreateView.as_view(), name='user-profile-create'),
        path('personal-profile/<int:pk>/update', views.UserProfileUpdateView.as_view(), name='user-profile-update'),
        path('personal-profile/<int:pk>/delete', views.UserProfileDeleteView.as_view(), name='user-profile-delete'),
        path('check-username', views.check_username_is_unique, name='check-username'),

]

article/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
# Create your models here.
from smartphone.models import Smartphone
from user_management.models import PlatformUser


class Article(models.Model):
    title = models.CharField(_('Titolo'), max_length=150)
    content = models.TextField(_('Testo'))
    created_by = models.ForeignKey(PlatformUser, on_delete=models.CASCADE, related_name='article_user_creator')
    img = models.ImageField(_("Immagine dell'articolo "), upload_to='article_images',blank=True,null=True)
    publish = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    smartphone = models.ForeignKey(Smartphone, on_delete=models.CASCADE, related_name='comment_article',blank=True,null=True)

    def __str__(self):
        return self.title

    @property
    def category(self):
        return "2"


class Comment(models.Model):
    user = models.ForeignKey(PlatformUser, on_delete=models.CASCADE, related_name='review_user_creator')
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comment_article')
    title = models.CharField(_('Titolo'), max_length=150)
    description = models.TextField(_('Testo'), max_length=300)
    like = models.ManyToManyField(PlatformUser, related_name='post_likes')

    def __str__(self):
        return self.title

    @property
    def total_likes(self):
        return self.like.count()

article/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Row, Column, Div, HTML
from django import forms

from article.models import Article, Comment


class ArticleForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_id = 'article-crispy-form'
        self.helper.form_method = 'POST'

        self.helper.layout = Layout(
            Div(
                Row(
                    Column('title', css_class='form-group mb-0'),
                    css_class='form-row'
                ),
                Row(
                    Column('content', css_class='form-group mb-0'),
                    css_class='form-row'
                ),
                Row(
                    Column('img', css_class='form-group mb-0'),
                    css_class='form-row'
                ),
                Row(
                    Column('smartphone', css_class='form-group mb-0'),
                    css_class='form-row'
                ),

                css_class='card-body')
        )

    class Meta:
        model = Article
        fields = ('title', 'content', 'img', 'smartphone')


class CommentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_id = 'comment-crispy-form'
        self.helper.form_method = 'POST'

        self.helper.layout = Layout(
            Div(
                Row(
                    Column('title', css_class='form-group mb-0'),
                    css_class='form-row'
                ),
                Row(
                    Column('description', css_class='form-group mb-0'),
                    css_class='form-row'
                ),

                css_class='card-body')
        )

    class Meta:
        model = Comment
        fields = ('title', 'description')

article/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.shortcuts import get_object_or_404

# Create your views here.
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.http import require_POST
from django.views.generic import CreateView, DeleteView, UpdateView, DetailView, ListView
from django.views.generic.edit import FormMixin, FormView

from article.forms import ArticleForm, CommentForm
from article.models import Article, Comment
from article.decorators import article_owner_only


class CreateArticleView(LoginRequiredMixin, CreateView):
    """
    View per la creazione di un nuovo articolo
    """

    template_name = 'article/article_add.html'
    form_class = ArticleForm

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        id = self.object.pk
        return reverse_lazy('article:article-detail', kwargs={'pk': id})


@method_decorator(article_owner_only, name='dispatch')
class UpdateArticleView(LoginRequiredMixin, UpdateView):
    """
    View per la modifica di un articolo esistente
    """

    template_name = 'article/article_update.html'
    model = Article
    form_class = ArticleForm

    def get_success_url(self):
        id = self.object.pk
        return reverse_lazy('article:article-detail', kwargs={'pk': id})

@method_decorator(article_owner_only, name='dispatch')
class DeleteArticleView(LoginRequiredMixin, DeleteView):
    """
    View per l'eliminazione di un articolo
    """
    model = Article
    success_url = reverse_lazy('article:article-list')


class NewCommentView(LoginRequiredMixin, FormView):
    """
    View per la creazione di un nuovo commento sotto ad un determinato articolo
    """

    form_class = CommentForm

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.article = Article.objects.get(pk=self.kwargs['pk'])
        self.object.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('article:article-detail', kwargs={'pk': self.kwargs['pk']})


class DetailArticleView(FormMixin, DetailView):
    """
    View per la visualizzazione di un articolo nel dettaglio
    """
    template_name = 'article/article_detail.html'
    model = Article
    form_class = CommentForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.get_form()
        context['comments'] = Comment.objects.filter(article=self.object)
        already_liked = []
        for comment in context['comments']:
            if comment.like.filter(id=self.request.user.pk).exists():
                already_liked.append(comment.id)
        context['already_liked'] = already_liked

        return context


class ArticleDetail(View):
    """View che unisce la visualizzazione di un articolo nel dettaglio con un form per inserire un nuovo commento
    sotto all'articolo stesso
    """

    def get(self, request, *args, **kwargs):
        view = DetailArticleView.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = NewCommentView.as_view()
        return view(request, *args, **kwargs)


class ListArticleView(ListView):
    """
    View per la creazione di una lista di articoli presenti sul sito
    """
    model = Article
    template_name = 'article/article_list.html'
    ordering = ['title']

    def get_ordering(self):
        ordering = self.request.GET.get('sort', 'title')
        return ordering


@login_required
@require_POST
def ajax_like_button(request):
    """
    Funzione ajax che implementa l'aggiunta di un like ad un commento
    :param request: richiesta ajax
    :return: risposta utilizzata per aggiornare il numero di like e cambiare colore all'icona
    """
    if request.POST.get("operation") == "like_submit":
        comment_pk = request.POST.get("comment_pk", None)
        comment = get_object_or_404(Comment, pk=comment_pk)
        if comment.like.filter(id=request.user.id):  # already liked the content
            comment.like.remove(request.user)  # remove user from likes
            liked = False
        else:
            comment.like.add(request.user)
            liked = True
        data = {"likes_count": comment.total_likes, "liked": liked, "comment_pk": comment_pk}
        return JsonResponse(data)

article/templates/article/article_add.html
{% extends 'base_operations.html' %}
{% load crispy_forms_tags %}
{% load static %}


{% block head_title %}Aggiunta nuovo articolo{% endblock %}

{% block title %}Nuovo articolo{% endblock %}

{% block mod_buttons %}
     <input class="btn btn-success m-1" type="submit" value="Aggiungi articolo">
                    <a class="btn btn-primary m-1" href="{% url 'home' %}">Ritorna alla home</a>
{% endblock %}

article/templates/article/article_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block head_title %}
    {{ object.title }}
{% endblock %}
{% block title %}
    {{ object.title }}

{% endblock %}
{% block content %}
    <div class="row justify-content-center">
        <div class="col-10 rounded shadow m-2">
            <div class="container-fluid">
                <div class="card-header text-center">
                    <span>Pubblicato :{{ article.publish }}<br>
                        {% if article.updated %} Ultimo aggiornamento : {{ article.updated }}{% endif %}</span>
                </div>
                <div class="card-body">
                    {% if object.created_by == user %}
                        <div class="text-right mb-5 mu-1">
                            <a class="btn btn-warning"
                               href="{% url 'article:article-update' object.pk%}">Modifica articolo</a>
                            <a class="btn btn-danger" id="card-delete-article"
                               href="#ArticleModal" data-bs-toggle="modal">Elimina articolo</a>
                        </div>
                    {% endif %}
                    <div class="row">
                        {% if article.img %}
                            <div class="col-lg-6 col-12 mu-10 mr-2 mb-2">
                                <img class="card-img " src="{{ object.img.url }}" alt="Nessuna immagine disponibile ">
                            </div>
                        {% endif %}
                        <div class="col-lg-6 col-12">
                            <p class="card-text">{{ object.content }}</p>
                            {% if article.smartphone %}
                                Link scheda tecnica <a class="card-link"
                                                       href="{% url 'smartphone:smartphone-detail' article.smartphone.pk %}">
                                {{ article.smartphone }} </a>

                            {% endif %}
                        </div>


                    </div>
                </div>
                <div class="card-footer ">
                    Scritto da <a class="card-link"
                                  href="{% url 'user_management:user-overview' article.created_by.pk %}">
                    {{ article.created_by.username }}</a>

                </div>
            </div>
        </div>




    </div>
    <div class="row p-1 justify-content-center ">
        <div class="col-10 rounded shadow m-2">
            {% include 'article/base/base_comment.html' with object=object %}
        </div>
    </div>
    <div class="row justify-content-center ">
        <div class="col-10 rounded shadow m-2 p-3">

            <h2 class="font-bold font-large text-center">Commenti</h2>

            {% for comment in comments %}
                <div class="container p-2">
                    <div class="row justify-content-center">
                        <div class="col-lg-6 col-12 rounded shadow">
                            <div class="row justify-content-center m-1">
                                <div class="col-lg-6 col-12 text-center">
                                    <h4 class="card-title text-center font-bold" >{{ comment.title }}</h4>
                                </div>
                            </div>
                            <div class="row justify-content-center m-1">
                                <div class="col-12">
                                    <p class="text-center">{{ comment.description }}</p>
                                </div>
                            </div>
                            <div class="row justify-content-center m-1">
                                <div class="col-12 like-container m-1">
                                <span data-comment-id="{{ comment.pk }}" class="likin" >
                                    <i class="fa fa-thumbs-up {% if comment.pk in already_liked %}liked{% endif %}"
                                       aria-hidden="true"></i></span>
                                    <span class="number-of-likes">{{ comment.total_likes }}</span>
                                </div>
                            </div>
                            <div class="row justify-content-center m-1">
                                <div class="col-12 card-footer text-muted m-3">
                                    <span>Postato da</span>
                                    <a href="{% url 'user_management:user-overview' comment.user.pk %}" class="card-link">{{ comment.user.username }}</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>



    <div id="ArticleModal" class="modal fade">
        <div class="modal-dialog modal-confirm">
            <div class="modal-content">
                <div class="modal-header">
                    <h4>Eliminare {{ object.title }} ? </h4>
                </div>
                <form method="POST" action="{%  url 'article:article-delete' object.pk %}">
                    {% csrf_token %}

                    <div class="modal-body">
                        <p>Questa azione non sarà reversibile</p>
                    </div>
                    <div class="modal-footer">
                        <input class='btn btn-success' type="submit" value ='Elimina '>
                        <a class='btn btn-danger' href="{% url 'article:article-detail' object.pk %}">Annulla</a>
                    </div>
                </form>

            </div>
        </div>
    </div>
    </div>

{% endblock %}

{% block javascript %}
    <script>
        // AJAX CALL
        $('.likin').click(function(){
            let selector = $(this).closest(".like-container").find(".fa-thumbs-up")
            let numselector = selector.closest(".like-container").find(".number-of-likes")
            $.ajax({
                type: "POST",
                url: "{% url 'article:article-like'%}",
                data: {'comment_pk': $(this).attr('data-comment-id'),'operation':'like_submit','csrfmiddlewaretoken': '{{ csrf_token }}'},
                dataType: "json",
                success: function(response) {
                    if(response.liked === true){
                        selector.toggleClass('liked')
                        console.log($(this));
                        numselector.text(response.likes_count);
                    }
                    else if(response.liked===false){
                        $(selector).toggleClass('liked')
                        numselector.text(response.likes_count);
                    }


                }

            });

        })
    </script>
{% endblock %}

article/templates/article/article_list.html
{% extends 'base.html' %}
{% load static %}
{% block head_title %}
    Articoli
{% endblock %}
{% block title %}
    Lista Articoli
{% endblock %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col-10">
            {%  if user.is_authenticated %}
                {% include 'article/base/order_by.html' %}
            {% endif %}
            {% include 'article/base/base_list.html' %}
        </div>
    </div>
{% endblock %}

article/templates/article/article_update.html
{% extends 'base_operations.html' %}
{% load crispy_forms_tags %}
{% load static %}


{% block head_title %}Modifica articolo{% endblock %}

{% block title %}Modifica articolo{% endblock %}

{% block mod_buttons %}
     <input class="btn btn-success" type="submit" value="Modifica articolo">
                    <a class="btn btn-primary ml-3" href="{% url 'article:article-detail' object.pk %}">Annulla</a>
{% endblock %}