PhoneAdvisor/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from PhoneAdvisor.views import HomePageView,SearchView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePageView.as_view(), name= 'home'),
    path('user_management/', include('user_management.urls')),
    path('smartphone/', include('smartphone.urls')),
    path('article/', include('article.urls')),
    path('search', SearchView.as_view(), name='global-search'),

]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

article/urls.py
from django.conf.urls.static import static
from django.urls import path
from article import views
from django.conf import settings
app_name = 'article'


urlpatterns = [
        path('add', views.CreateArticleView.as_view(), name='article-add'),
        path('list', views.ListArticleView.as_view(), name='article-list'),
        path('<int:pk>/update', views.UpdateArticleView.as_view(), name='article-update'),
        path('<int:pk>/delete', views.DeleteArticleView.as_view(), name='article-delete'),
        path('<int:pk>/detail', views.ArticleDetail.as_view(), name='article-detail'),
        path('like', views.ajax_like_button, name='article-like'),

]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

smartphone/urls.py
from django.conf.urls.static import static
from django.urls import path
from smartphone import views
from django.conf import settings
app_name = 'smartphone'


urlpatterns = [
        path('add', views.CreateSmartphoneView.as_view(), name='smartphone-add'),
        path('list', views.ListSmartphoneView.as_view(), name='smartphone-list'),
        path('<int:pk>/update', views.UpdateSmartphoneView.as_view(), name='smartphone-update'),
        path('<int:pk>/delete', views.DeleteSmartphoneView.as_view(), name='smartphone-delete'),
        path('<int:pk>/detail', views.SmartphoneDetail.as_view(), name='smartphone-detail'),
        path('check-smartphone-name', views.check_smartphone_name_is_unique, name='check-smartphone-name'),
        # path('rate', views.rate_smartphone, name='rate-smartphone'),
        # path('search', views.SmartphoneSearchView.as_view(), name='smartphone-search'),
        path('compare/<int:first_pk>/<int:second_pk>/<int:third_pk>', views.CompareSmartphoneView.as_view(), name='smartphone-compare'),

]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

user_management/urls.py
from django.conf.urls.static import static
from django.urls import path
from user_management import views
from django.conf import settings
app_name = 'user_management'


urlpatterns = [
        path('registration', views.UserCreateView.as_view(), name='user-register'),
        path('login', views.LoginUserView.as_view(), name='user-login'),
        path('logout', views.LogoutUserView.as_view(), name='user-logout'),
        path('list', views.ListUserView.as_view(), name='user-list'),
        path('profile/<int:pk>', views.ProfileView.as_view(), name='user-overview'),
        path('profile/<int:pk>/update', views.UserUpdateView.as_view(), name='user-update'),
        path('profile/<int:pk>/delete', views.UserDeleteView.as_view(), name='user-delete'),
        path('personal-profile/create', views.UserProfileCreateView.as_view(), name='user-profile-create'),
        path('personal-profile/<int:pk>/update', views.UserProfileUpdateView.as_view(), name='user-profile-update'),
        path('personal-profile/<int:pk>/delete', views.UserProfileDeleteView.as_view(), name='user-profile-delete'),
        path('check-username', views.check_username_is_unique, name='check-username'),

]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>


    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">



    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1"
          crossorigin="anonymous">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
          integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p"
          crossorigin="anonymous"/>



    <!-- My stylesheet -->
    <link rel = "stylesheet" href={% static "css/style.css" %}>
    <title>{% block head_title %}{% endblock %}</title>
    <!-- Google Font -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&display=swap" rel="stylesheet">

     <!-- Favicon -->
    <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.png' %}">
</head>
<body >
{%  include 'navbar.html' %}
<div id="site-main-page" class="{% block background_class %}{% endblock %} container-fluid">

    <div class="font-large font-bold text-center p-3">
{% block title %}{% endblock %}
</div>

    {% block content %}

    {% endblock %}

</div>


<script
        src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"
        integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js"
        integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj"
        crossorigin="anonymous"></script>

<script src="{% static 'js/main.js' %}"></script>
{% block javascript %}{% endblock %}
</body>
</html>

templates/base_operations.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col-10 d-flex justify-content-center">
            <form method="post" enctype="multipart/form-data">{% csrf_token %}
                <div class="row justify-content-lg-between justify-content-center rounded shadow m-2 p-5 text-center">


                    {% crispy form %}
                    <div class="row justify-content-center p-3">
                        <div class="col-lg-7 col-auto ">
                            {% block mod_buttons %}

                            {% endblock %}
                        </div>
                    </div>

                </div>
            </form>
        </div>
    </div>



{% endblock %}

templates/homepage.html
{% extends 'base.html'%}
{% load static %}
{% block head_title  %}Homepage{% endblock %}
{% block background_class %}bg-home{% endblock %}
{% block content %}
    <div class="row mt-4 pt-3 p-2">

        <div class="col">
                <h1 class=" text-white text-center greetings mb-0 font-weight-bold">Benvenuto su PhoneAdvisor.</h1>
        </div>
    </div>
    <div class="row p-2">

        <div class="col">
                <h5 class=" text-white text-center greetings">Dai un'occhiata al riepilogo</h5>
        </div>
    </div>

    <div class="row p-5 justify-content-center">

        <div class="col-lg-4 col-10 d-flex justify-content-center p-2">
            <a type="button" class="btn-lg btn-success btn" href="{% url 'smartphone:smartphone-add' %}">
                Inserisci una scheda tecnica
            </a>
        </div>
        <div class="col-lg-4 col-10 d-flex justify-content-center p-2">
            <a type="button" class="btn-lg btn-success btn" href="{% url 'smartphone:smartphone-compare' 0 0 0 %}">
                Compara smartphone
            </a>
        </div>
        <div class="col-lg-4 col-10 d-flex justify-content-center p-2">
            <a type="button" class="btn-lg btn-success btn" href="{% url 'article:article-add' %}">
                Inserisci un articolo
            </a>

        </div>
    </div>

    <div class="row p-4-lg p-2 justify-content-center">

        <div id="homepage-summary-first-box" class="col-lg-5 col-10 box-width-radius2 rounded shadow m-3 p-2 bg-white">
            <h2 class="m-2 font-bold text-center">5 smartphone meglio classificati </h2>
            {% include 'smartphone/base/base_list.html'  with object_list=recent_smartphones %}
        </div>

        <div id="homepage-summary-second-box" class="col-lg-5 col-10 box-width-radius2 rounded shadow m-3 p-2 bg-white">
            <h2 class="m-2 font-bold text-center ">5 Articoli più recenti </h2>
            {% include 'article/base/base_list.html'  with object_list=recent_articles %}
    </div>
    </div>


{% endblock %}

templates/navbar.html
{% url 'smartphone:smartphone-compare' as compare_url %}
{%  load static %}

<nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-between p-3">

    <div class="d-lg-none col-12 col-lg-1 d-flex justify-content-lg-start justify-content-center align-items-center">
        <button class="btn btn-light toggler d-flex align-items-center" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggleExternalContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span    class="font-bold"><img src="{% static "img/business.png" %}" width="60" height="30" alt=""></span>
        </button>
    </div>

    <div class="col-12 col-lg-5">
        <div class="collapse navbar-collapse" id="navbarToggleExternalContent">
            <ul class="navbar-nav mr-auto text-center ">
                <li class="d-xl-none d-lg-none d-md-block d-sm-block d-xs-block nav-item d-flex justify-content-lg-start justify-content-center">
                    <a class="nav-link font-bold" href="{% url 'home'%}">Home
                        <span class="sr-only">(current)</span></a>
                </li>
                <li class="d-none d-lg-block d-xl-block nav-item d-flex justify-content-lg-start justify-content-center">
                    <a class="nav-link font-bold" href="{% url 'home'%}">
                        <img src="{% static "img/business.png" %}" width="60" height="30" alt=""></a>
                </li>
                <li class="nav-item d-flex justify-content-lg-start justify-content-center">
                    <a class="nav-link font-bold" href="{% url 'user_management:user-list' %}">Utenti</a>
                </li>
                <li class="nav-item d-flex justify-content-lg-start justify-content-center">
                    <a class="nav-link font-bold" href="{% url 'smartphone:smartphone-add' %}">Nuova scheda tecnica</a>
                </li>
                <li class="nav-item d-flex justify-content-lg-start justify-content-center">
                    <a class="nav-link font-bold" href="{% url 'smartphone:smartphone-list' %}">Schede tecniche</a>
                </li>
                <li class="nav-item d-flex justify-content-lg-start justify-content-center">
                    <a class="nav-link font-bold" href="{% url 'article:article-add' %}">Nuovo articolo</a>
                </li>
                <li class="nav-item d-flex justify-content-lg-start justify-content-center">
                    <a class="nav-link font-bold" href="{% url 'article:article-list' %}">Articoli</a>
                </li>
                <li class="nav-item d-flex justify-content-lg-start justify-content-center">
                    <a class="nav-link font-bold" href="{% url 'smartphone:smartphone-compare' 0 0 0 %}">Compara</a>
                </li>
            </ul>
        </div>
    </div>

    <div class="col-12 col-lg-4 d-flex justify-content-lg-center justify-content-center">
        {% if not request.get_full_path == compare_url%}
            {% include 'searchbar.html' with compare=False %}
        {% endif %}
    </div>

    <div class="col-12 col-lg-2 d-flex justify-content-lg-end justify-content-center">
            <div class="row m-2 justify-content-center">
                {% if user.is_authenticated %}
                    <div class="col-12 d-flex justify-content-end">
                        <a class="btn btn-sm btn-outline-secondary m-1" href="{% url 'user_management:user-overview' user.pk%}"
                           role="button">{{ user.username }}</a>
                        <a class="btn btn-sm btn-outline-secondary m-1" href="{% url 'user_management:user-logout' %}"
                           role="button">Logout</a>
                    </div>
                {% else %}
                    <div class="col-12 d-flex justify-content-end">
                        <a class="btn btn-sm btn-outline-secondary m-1" href="{% url 'user_management:user-register' %}"
                           role="button">Registrati</a>
                        <a class="btn btn-sm btn-outline-secondary m-1" href="{% url 'user_management:user-login' %}"
                           role="button">Login</a>
                    </div>


                {% endif %}
            </div>

    </div>




</nav>

templates/results_list.html
{% extends 'base.html' %}
{% block head_title %}
    {% if query %}
        Risultati per {{ query }}
    {% else %}
        Risultati
    {% endif %}

{% endblock %}
{% block content %}
    <div class="container-fluid">


            {%  if object_list %}
                {% for object in object_list %}
                    <div class="row">
                        <div class="col d-flex justify-content-center rounded shadow p-4-lg m-3-lg mb-2 bg-white w-auto">
                            <div class="rounded w-100 m-1 p-1">
                                {% if object.category == "1" %}
                                    {%  include 'smartphone/base/list_element.html' with smartphone=object %}


                                {% elif object.category == "2"%}
                                    {% include 'article/base/list_element.html'  with article=object %}

                                {% elif object.category == "3"%}
                                    {% include 'user_management/base/list_element.html' with object=object%}
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {%  else %}
                <div class="row">
                    <div class="col d-flex justify-content-center p-4-lg m-3-lg mb-2 bg-white w-auto">
                        <span class="text-center font-bold font-large">Nessun Risultato</span>
                    </div>
                </div>
            {%  endif %}
    </div>
{% endblock %}

templates/searchbar.html
{% load static %}

{% if compare %}

    <form id="{{ searchbar_form_id }}" class="my-2 my-lg-0"
          action="{% url 'smartphone:smartphone-compare' first_pk second_pk third_pk %}">
    <div class="row">
    {% comment %} {% elif  page_exist%}
                action="{% url 'smartphone:smartphone-compare' mypage page %}"> {% endcomment %}
{% else %}

    <form id="{{ searchbar_form_id }}" class="my-2 my-lg-0" method="GET"
          action="{% url 'global-search' %}" >
    <div class="row">
    <div class="col-5 auto p-0">
        <select id='searchbar-categories' class="form-select mx-1 btn-success" data-style="btn-success" name="category" >
            <option selected value="0">Qualsiasi categoria</option>
            <option value="1">Smartphone</option>
            <option value="2">Articoli</option>
            <option value="3">Utenti</option>
        </select>
    </div>

{% endif %}

{% if compare %}
    <div class="col-10 p-0 mx-1">
{% else %}
    <div class="col-5 p-0 mx-1">
{% endif %}

<input class="search-field form-control mx-1" type="search"
       placeholder="Cerca..." aria-label="Cerca" name="{{ search_name|default:"search"  }}" style="width: 100%">
</div>
<div class="col-1 p-0 d-flex align-items-center">
    <button class="btn btn-success mx-1"  type="submit">
        <i class="fas fa-search "></i>
    </button>
</div>


</div>
</form>
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="{% static 'js/searchbar.js' %}"></script>