PhoneAdvisor/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from PhoneAdvisor.views import HomePageView,SearchView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePageView.as_view(), name= 'home'),
    path('user_management/', include('user_management.urls')),
    path('smartphone/', include('smartphone.urls')),
    path('article/', include('article.urls')),
    path('search', SearchView.as_view(), name='global-search'),

]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

article/urls.py
from django.conf.urls.static import static
from django.urls import path
from article import views
from django.conf import settings
app_name = 'article'


urlpatterns = [
        path('add', views.CreateArticleView.as_view(), name='article-add'),
        path('list', views.ListArticleView.as_view(), name='article-list'),
        path('<int:pk>/update', views.UpdateArticleView.as_view(), name='article-update'),
        path('<int:pk>/delete', views.DeleteArticleView.as_view(), name='article-delete'),
        path('<int:pk>/detail', views.ArticleDetail.as_view(), name='article-detail'),
        path('like', views.ajax_like_button, name='article-like'),

]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

smartphone/urls.py
from django.conf.urls.static import static
from django.urls import path
from smartphone import views
from django.conf import settings
app_name = 'smartphone'


urlpatterns = [
        path('add', views.CreateSmartphoneView.as_view(), name='smartphone-add'),
        path('list', views.ListSmartphoneView.as_view(), name='smartphone-list'),
        path('<int:pk>/update', views.UpdateSmartphoneView.as_view(), name='smartphone-update'),
        path('<int:pk>/delete', views.DeleteSmartphoneView.as_view(), name='smartphone-delete'),
        path('<int:pk>/detail', views.SmartphoneDetail.as_view(), name='smartphone-detail'),
        path('check-smartphone-name', views.check_smartphone_name_is_unique, name='check-smartphone-name'),
        # path('rate', views.rate_smartphone, name='rate-smartphone'),
        # path('search', views.SmartphoneSearchView.as_view(), name='smartphone-search'),
        path('compare/<int:first_pk>/<int:second_pk>/<int:third_pk>', views.CompareSmartphoneView.as_view(), name='smartphone-compare'),

]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

user_management/urls.py
from django.conf.urls.static import static
from django.urls import path
from user_management import views
from django.conf import settings
app_name = 'user_management'


urlpatterns = [
        path('registration', views.UserCreateView.as_view(), name='user-register'),
        path('login', views.LoginUserView.as_view(), name='user-login'),
        path('logout', views.LogoutUserView.as_view(), name='user-logout'),
        path('list', views.ListUserView.as_view(), name='user-list'),
        path('profile/<int:pk>', views.ProfileView.as_view(), name='user-overview'),
        path('profile/<int:pk>/update', views.UserUpdateView.as_view(), name='user-update'),
        path('profile/<int:pk>/delete', views.UserDeleteView.as_view(), name='user-delete'),
        path('personal-profile/create', views.UserProfileCreateView.as_view(), name='user-profile-create'),
        path('personal-profile/<int:pk>/update', views.UserProfileUpdateView.as_view(), name='user-profile-update'),
        path('personal-profile/<int:pk>/delete', views.UserProfileDeleteView.as_view(), name='user-profile-delete'),
        path('check-username', views.check_username_is_unique, name='check-username'),

]

smartphone/models.py
import string
from statistics import mean

from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.db.models import Avg
from django.utils.translation import gettext_lazy as _

from smartphone.utils import name_to_template
from user_management.models import PlatformUser


class Brand(models.Model):
    name = models.CharField(_('Brand'), unique=True, max_length=150)

    def __repr__(self):
        return self.name

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


class Smartphone(models.Model):
    created_by = models.ForeignKey(PlatformUser, on_delete=models.CASCADE, related_name='user_creator')
    os_type = (
        ('IOS', 'iOS'),
        ('ANDROID', 'Android')
    )
    name = models.CharField(_('Nome'), max_length=150, unique=True)
    size_width = models.FloatField(_('Larghezza (mm)'), max_length=150)
    size_height = models.FloatField(_('Altezza (mm)'), max_length=150)
    size_depth = models.FloatField(_('Spessore (mm)'), max_length=150)
    os = models.CharField(_('Sistema Operativo'), max_length=10, choices=os_type)
    os_version = models.FloatField(_('Versione'), )
    weight = models.FloatField(_('Peso (g)'), max_length=150)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, related_name='phone_brand')
    img = models.ImageField(('Immagine dello Smartphone'), upload_to='smartphone_images')

    # NETWORK

    sim_models = (
        ('STANDARD', 'Standard'),
        ('NANO', 'Nano'),
        ('MICRO', 'Micro'),
    )
    sim = models.CharField(max_length=10, choices=sim_models)
    dual_sim = models.BooleanField()
    lte = models.BooleanField(_('LTE'), )
    g_5 = models.BooleanField(_('5G'), )
    max_download_speed = models.IntegerField(_('Max velocità download (Mbps)'))
    min_download_speed = models.IntegerField(_('Min velocità download (Mbps)'), null=True, blank=True)

    # SPECS

    processor = models.CharField(_('Processore'), max_length=50)
    # gpu = models.CharField(_('Scheda Grafica') , max_length=50)
    bit_64 = models.BooleanField(_('64 Bit'))
    ram = models.IntegerField(_('Ram (Gb)'))
    rom = models.IntegerField(_('Memoria max (Gb)'), )
    exp_mem = models.BooleanField(_('Memoria Espandibile '), )
    battery_mah = models.IntegerField(_('Batteria (Mah)'))

    # DISPLAY
    type = (
        ('IPS LCD', 'IPS LCD'),
        ('AMOLED', 'AMOLED'),
        ('OLED', 'OLED'),
    )
    display_inches = models.FloatField(_('Dimensioni schermo (pollici)'), )
    display_resolution_width = models.FloatField(_('Larghezza schermo (px)'))
    display_resolution_height = models.FloatField(_('Altezza schermo (px)'))
    display_type = models.CharField(_('Tipo schermo'), max_length=10, choices=type)
    display_colors = models.IntegerField(_('Colori schermo (milioni)'), default=16)
    display_protection = models.CharField(_('Tipo di vetro'), default='Gorilla Glass 5', max_length=50)

    # CAMERA
    camera_megapixel_rear = models.IntegerField(_('Megapixel camera posteriore'))
    camera_megapixel_front = models.IntegerField(_('Megapixel camera frontale '))

    camera_stabilization = models.BooleanField(_('Stabilizzazione'))
    camera_autofocus = models.BooleanField(_('Autofocus'))
    camera_flash = models.BooleanField(_('Flash'))
    camera_hdr = models.BooleanField(_('HDR'))
    camera_geo_tagging = models.BooleanField(_('Geo Tagging'))
    camera_face_detection = models.BooleanField(_('Face Detection'))

    # VIDEO
    resolution = (
        ('HD', '720 HD'),
        ('FULL HD', '1080 FULL HD'),
        ('4K', '4K'),
        ('8K', '8K'),
    )
    video_resolution_rear = models.CharField(_('Qualità video posteriore'), max_length=10, choices=resolution)
    video_resolution_front = models.CharField(_('Qualità video frontale'), max_length=10, choices=resolution)
    video_autofocus = models.BooleanField(_('Autofocus'))
    video_stabilization = models.BooleanField(_('Stabilizzazione'))
    video_fps = models.IntegerField(_('FPS'))
    video_slowmotion = models.BooleanField(_('SlowMotion'))

    # CONNECTIVITY

    usb_type = (
        ('MICRO USB', 'MICRO USB'),
        ('TYPE C', 'TYPE C'),
        ('LIGHTNING', 'LIGHTNING'),
    )
    wifi = models.BooleanField(_('Wifi'))
    bluetooth = models.BooleanField(_('Bluetooth'))
    nfc = models.BooleanField(_('NFC'))
    gps = models.BooleanField(_('Gps'))
    usb = models.CharField(max_length=10, choices=usb_type)

    # SENSORS

    accelerometer = models.BooleanField(_('Accelerometro'))
    proximity = models.BooleanField(_('Prossimità'))
    gyroscope = models.BooleanField(_('Giroscopio'))
    compass = models.BooleanField(_('Bussola'))
    barometer = models.BooleanField(_('Barometro'))
    fingerprint = models.BooleanField(_('Impronta Digitale'))

    def __str__(self):
        return name_to_template(self.name)

    @property
    def mean_rating(self):
        if Review.objects.filter(smartphone=self).exists():
            return int(self.reviews_smartphone.exclude(rating=None).aggregate(Avg('rating'))['rating__avg'])
        else:
            return 0

    @property
    def category(self):
        return "1"


class Review(models.Model):
    created_by = models.ForeignKey(PlatformUser, on_delete=models.CASCADE, related_name='review_creator', default='1')
    smartphone = models.ForeignKey(Smartphone, on_delete=models.CASCADE, related_name='reviews_smartphone')
    title = models.CharField(_('Titolo'), max_length=150)
    description = models.TextField(_('Testo'), max_length=300)
    rating = models.PositiveSmallIntegerField(_('Stelle'), default=1,
                                              validators=[MinValueValidator(1), MaxValueValidator(5)])

    def __str__(self):
        return self.title

smartphone/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Row, Column, Div, HTML
from django import forms

from smartphone.models import Smartphone, Review


class SmartphoneSpecsForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_id = 'smartphone-crispy-form'
        self.helper.form_method = 'POST'

        self.helper.layout = Layout(
            Div(
                HTML('''<h4 class="font-bold">GENERALI</h4>'''),
                Div('img', css_class='form-row mb-0  m-2'),
                Div('name', css_class='form-row mb-0  m-2 '),

                Div(css_id='smartphone-check'),

                Div(
                    Div('size_width', css_class='m-2'),
                    Div('size_height', css_class='m-2'),
                    Div('size_depth', css_class='m-2'),
                    css_class='form-row '),
                Div(
                    Div('os', css_class='m-2'),
                    Div('os_version', css_class='m-2'),
                    css_class='form-row '),
                Div('weight', css_class=' m-2 form-row mb-0'),
                Div('brand', css_class=' m-2 form-row mb-0'),

                css_class='col-lg-5 col-8 shadow p-1 m-3'),

            Div(
                HTML('''<h4 class="card-title">RETE</h4>'''),
                Div('sim', css_class='m-2 form-row mb-0'),
                Div('dual_sim', css_class='m-2 form-row mb-0'),
                Div('lte', css_class='m-2 form-row mb-0'),
                Div('g_5', css_class='m-2 form-row mb-0'),
                Div('max_download_speed', css_class='m-2 form-row mb-0'),
                Div('min_download_speed', css_class='m-2 form-row mb-0'),

                css_class='col-lg-5 col-8 shadow p-1 m-3'),

            Div(
                HTML('''<h4 class="card-title">SPECIFICHE</h4>'''),
                Div('processor', css_class='form-group mb-0 m-2'),
                Div('bit_64', css_class='form-group mb-0 m-2'),
                Div('ram', css_class='form-group mb-0 m-2'),
                Div('rom', css_class='form-group mb-0 m-2'),
                Div('exp_mem', css_class='form-group mb-0 m-2'),
                Div('battery_mah', css_class='form-group mb-0 m-2'),

                css_class='col-lg-5 col-8 shadow p-1 m-3'),

            Div(
                HTML('''<h4 class="card-title">DISPLAY</h4>'''),
                Div('display_inches', css_class='form-group mb-0 m-2'),
                Div(
                    Div('display_resolution_width', css_class='m-2'),
                    Div('display_resolution_height', css_class='m-2'),
                    css_class='form-row '),
                Div('display_type', css_class='form-group mb-0 m-2'),
                Div('display_colors', css_class='form-group mb-0 m-2'),
                Div('display_protection', css_class='form-group mb-0 m-2'),

                css_class='col-lg-5 col-8 shadow p-1 m-3'),

            Div(
                HTML('''<h4 class="card-title">FOTO</h4>'''),
                Div('camera_megapixel_rear', css_class='form-group mb-0 m-2'),
                Div('camera_megapixel_front', css_class='form-group mb-0 m-2'),
                Div('camera_stabilization', css_class='form-group mb-0 m-2'),
                Div('camera_autofocus', css_class='form-group mb-0 m-2'),
                Div('camera_flash', css_class='form-group mb-0 m-2'),
                Div('camera_hdr', css_class='form-group mb-0 m-2'),
                Div('camera_geo_tagging', css_class='form-group mb-0 m-2'),
                Div('camera_face_detection', css_class='form-group mb-0 m-2'),

                css_class='col-lg-5 col-8 shadow p-1 m-3'),

            Div(
                HTML('''<h4 class="card-title">VIDEO</h4>'''),
                Div('video_resolution_rear', css_class='form-group mb-0 m-2'),
                Div('video_resolution_front', css_class='form-group mb-0 m-2'),
                Div('video_autofocus', css_class='form-group mb-0 m-2'),
                Div('video_stabilization', css_class='form-group mb-0 m-2'),
                Div('video_fps', css_class='form-group mb-0 m-2'),
                Div('video_slowmotion', css_class='form-group mb-0 m-2'),

                css_class='col-lg-5 col-8 shadow p-1 m-3'),

            Div(
                HTML('''<h4 class="card-title">CONNETTIVITA'</h4>'''),
                Div('wifi', css_class='form-group mb-0'),
                Div('bluetooth', css_class='form-group mb-0 m-2'),
                Div('nfc', css_class='form-group mb-0 m-2'),
                Div('gps', css_class='form-group mb-0 m-2'),
                Div('usb', css_class='form-group mb-0 m-2'),

                css_class='col-lg-5 col-8 shadow p-1 m-3'),

            Div(
                HTML('''<h4 class="card-title">SENSORI</h4>'''),
                Div('accelerometer', css_class='form-group mb-0 m-2'),
                Div('proximity', css_class='form-group mb-0 m-2'),
                Div('gyroscope', css_class='form-group mb-0 m-2'),
                Div('compass', css_class='form-group mb-0 m-2'),
                Div('barometer', css_class='form-group mb-0 m-2'),
                Div('fingerprint', css_class='form-group mb-0 m-2'),

                css_class='col-lg-5 col-8 shadow p-1 m-3'),
        )

    class Meta:
        model = Smartphone
        fields = '__all__'
        exclude = ['created_by']


class ReviewForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_id = 'review-crispy-form'
        self.helper.form_method = 'POST'

        self.helper.layout = Layout(
            Div(
                Row(
                    Column('title', css_class='form-group mb-0'),
                    css_class='form-row'
                ),
                Row(
                    Column('description', css_class='form-group mb-0'),
                    css_class='form-row'
                ),
                Row(
                    Column(
                        HTML(''' <span class="fa fa-star checked" id="first"></span>
                                             <span class="fa fa-star " id="second"></span>
                                             <span class="fa fa-star " id="third"></span>
                                             <span class="fa fa-star" id="fourth"></span>
                                             <span class="fa fa-star" id="fifth"></span>'''),
                    ),
                ),
                css_class='card-body text-center')
        )

    class Meta:
        model = Review
        fields = ('title', 'description')

smartphone/templates/smartphone/compare_smartphone.html
{% extends 'base.html' %}
{% load static %}

{% block head_title %}
    Confronta Smartphone
{% endblock %}
{% comment %}
    Page for displaying compare data relating to the analysis of two texts
{% endcomment %}

{% block title %}Confronto schede tecniche{% endblock %}

{% block content %}
    <div id='compare' class="row justify-content-center">
        <div class="col-lg-4 col-12">
            <div class="container-fluid rounded shadow pb-5">
                <div class="row">
                    <div class="col d-flex justify-content-around p-3">
                        {% with search_name='search1' first_pk=0 second_pk=second_pk third_pk=third_pk%}
                            {% include 'searchbar.html' with compare=True%}
                        {% endwith %}
                    </div>
                </div>
                {% if not first_clicked %}
                    {% for smartphone in first_list %}
                        <div class="row">
                            <div class="col-12 ">
                                <div class="list-group w-100 text-center m-2">
                                    <a href="{%  url 'smartphone:smartphone-compare' smartphone.pk second_pk third_pk%}" class="list-group-item list-group-item-action">
                                        {{ smartphone.name }}
                                    </a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
                {% if first_pk != 0 %}
                    {% include 'smartphone/base/base_detail.html' with object=first_smartphone compare=True%}
                {% endif %}
            </div>
        </div>

        <div class="col-lg-4 col-12">
            <div class="container-fluid rounded shadow pb-5">
                <div class="row ">
                    <div class="col  d-flex justify-content-around p-3">
                        {% with search_name='search2' first_pk=first_pk second_pk=0 third_pk=third_pk%}
                            {% include 'searchbar.html' with compare=True%}
                        {% endwith %}
                    </div>
                </div>
                {% if not second_clicked %}
                    {% for smartphone in second_list %}
                        <div class="row">
                            <div class="col-12 ">
                                <div class="list-group w-100 text-center m-2">
                                    <a href="{%  url 'smartphone:smartphone-compare' first_pk smartphone.pk third_pk%}" class="list-group-item list-group-item-action">
                                        {{ smartphone.name }}
                                    </a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
                {% if second_pk != 0 %}
                    {% include 'smartphone/base/base_detail.html' with object=second_smartphone compare=True%}
                {% endif %}
            </div>
        </div>

        <div class="col-lg-4 col-12">
            <div class="container-fluid rounded shadow pb-5">
                <div class="row">
                    <div class="col d-flex justify-content-around p-3">
                        {% with search_name='search3' first_pk=first_pk second_pk=second_pk third_pk=0 %}
                            {% include 'searchbar.html' with compare=True%}
                        {% endwith %}
                    </div>
                </div>
                {% if not third_clicked %}
                    {% for smartphone in third_list %}
                        <div class="row">
                            <div class="col-12 ">
                                <div class="list-group w-100 text-center m-2">
                                    <a href="{%  url 'smartphone:smartphone-compare' first_pk second_pk smartphone.pk %}" class="list-group-item list-group-item-action">
                                        {{ smartphone.name }}
                                    </a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
                {% if third_pk != 0 %}
                    {% include 'smartphone/base/base_detail.html' with object=third_smartphone avg_rating=avg_rating_3 compare=True %}
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}

smartphone/templates/smartphone/review_list.html
{% load static %}

<div class="container rounded shadow p-4">
    <div class="row">
        {% if reviews %}
        <h2 class="font-bold font-large text-center m-3">Recensioni</h2>
        {% else %}
            <h2 class="font-bold font-large text-center m-3">Nessuna recensione presente</h2>
        {% endif %}
    </div>
    <div class="row">

<div class="col ">
        <ul class="list-group list-group-flush">
            {% for review in reviews %}
                    <div class="card mr-2 ml-2 mu-2 mb-2 ">
                        <div class="card-body text-center">
                            <h5 class="card-title font-bold">{{ review.title }}</h5>
                             <h6 class="card-subtitle mb-2 text-muted">{{ review.rating }} <i class="fas fa-star review "></i></h6>
                            <p class="card-text">{{ review.description }}</p>
                            <a href="{% url 'user_management:user-overview' review.created_by.pk %}" class="card-link">{{ review.created_by.username }}</a>
                        </div>
                    </div>
                {% endfor %}

            </ul>

        </div>

</div>
</div>

smartphone/templates/smartphone/smartphone_add.html
{% extends 'base_operations.html' %}
{% load crispy_forms_tags %}
{% load static %}


{% block head_title %}Aggiunta nuovo smartphone{% endblock %}

{% block title %}Nuovo smartphone{% endblock %}

{% block mod_buttons %}
    <input class="btn btn-success mx-3 my-2" type="submit" value="Aggiungi smartphone">
    <a class="btn btn-primary mx-3 my-2" href="{% url 'home' %}">Ritorna alla home</a>
{% endblock %}

{% block javascript %}
    <script>
        $( "#id_name" ).change(function() {
            let smartphone_name=$(this).val();
            if(smartphone_name!==''){
                $.ajax({
                    url:'{% url 'smartphone:check-smartphone-name' %}',
                    type: 'GET',
                    data : { smartphone_name : smartphone_name },
                    dataType: 'json',
                    success: function (data) {
                        let smartphone_name_field = $('#id_name');
                        let smartphone_name_info = $('#smartphone-check');
                        if (data.is_used) {

                            smartphone_name_field.css('border-color', "#CC0000");
                            if ($('#smartphone-not-used').length) {
                                $('#smartphone-not-used').remove()
                            }
                            smartphone_name_info.append(
                                '<span id="smartphone-used" class="text-danger font-7 font-size-80">' +
                                'Telefono già inserito <br></span>'

                            );


                        }
                        else {
                            smartphone_name_field.css('border-color', "#00CC99");
                            if ($('#smartphone-used').length) {
                                $('#smartphone-used').remove()
                            }
                            smartphone_name_info.append(
                                '<span id="smartphone-not-used" class="text-success font-7 font-size-80">' +
                                ' Telefono non ancora inserito <br></span>'

                            );


                        }

                    },
                    error:function (data){
                    },

                })
            }


        });
    </script>
{% endblock %}

smartphone/templates/smartphone/smartphone_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Elimina Smartphone
{% endblock %}
{% block content %}
    <h4>{{ object.first_name }} vuoi davvero eliminare questa scheda tecnica ?</h4>
    <form method="POST">
        {% csrf_token %}

    <input class='btn btn-success' type="submit" value ='Elimina '>
        <a class='btn btn-danger' href="{% url 'smartphone:smartphone-list'%}">Annulla</a>
    </form>
{% endblock %}

smartphone/templates/smartphone/smartphone_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block head_title %}
{{ object.name }}
{% endblock %}

{% block title %}
{{ object.name }}
{% endblock %}

{% block content %}
    <div class="container">
    <div class="row ">
        <div class="col">
            <div class="container-fluid rounded shadow p-5">
        {% include 'smartphone/base/base_detail.html' with object=object %}
            </div>
        </div>
    </div>
        {% if user.is_authenticated %}
        <div class="mb-5 mu-5">
        {% include 'smartphone/base/base_review.html' with object=object %}
    </div>
        {% endif %}
    <div class="mb-5 mu-5" >
        {% include 'smartphone/review_list.html' with reviews=reviews%}
    </div>




{% endblock %}

smartphone/templates/smartphone/smartphone_list.html
{% extends 'base.html' %}
{% load static %}
{% block head_title %}
    Schede tecniche
{% endblock %}

{% block title %}
    Lista Schede Tecniche
{% endblock %}
{% block content %}
    <div class="row justify-content-center">
        <div class="col-10">
            {%  if user.is_authenticated %}
                {%  include 'smartphone/base/order_by.html' %}
            {% endif %}
            {% include 'smartphone/base/base_list.html' %}
        </div>
    </div>
{% endblock %}

smartphone/templates/smartphone/smartphone_update.html
{% extends 'base_operations.html' %}
{% load crispy_forms_tags %}
{% load static %}


{% block head_title %}Modifica smartphone{% endblock %}

{% block title%}Modifica smartphone{% endblock %}

{% block mod_buttons %}
 <input class="btn btn-success" type="submit" value="Modifica smartphone">
                    <a class="btn btn-primary ml-3" href="{% url 'smartphone:smartphone-detail' object.pk%}">Annulla</a>
{% endblock %}

{% block javascript %}
<script>
    $( "#id_name" ).change(function() {
        let smartphone_name=$(this).val();
        if(smartphone_name!==''){
        $.ajax({
            url:'{% url 'smartphone:check-smartphone-name' %}',
            type: 'GET',
            data : { smartphone_name : smartphone_name },
            dataType: 'json',
            success: function (data) {
                        let smartphone_name_field = $('#id_name');
                        if (data.is_used) {

                            smartphone_name_field.css('border-color', "#CC0000");
                            if(!$('#smartphone_name-exists-error').length) {
                                smartphone_name_field.after(
                                    ' <span id="smartphone_name-exists-error" class="text-danger font-7 font-size-80">' +
                                    'Modello già inserito' +
                                    '</span>'
                                );
                            }

                        }
                        else {
                            smartphone_name_field.css('border-color', "#00CC99");
                            $('#smartphone_name-exists-error').remove();

                        }

                    },
                    error:function (data){
                    },

                })
            }


        });
</script>
{% endblock %}